import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import "../globals.css";

import Navbar from './_components/Navbar';
import About from './_components/About';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Guess that City',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <head>
        <title>Guess That City!</title>
      </head>
      <body className={inter.className +" h-fit relative"}>
        <div className="z-10 absolute bg-orange-400 h-full md:w-12 w-8 rounded-br-full -top-12">
            <div className=" bg-orange-600 h-full md:w-6 w-4 rounded-br-full absolute -top-4">
            </div>
        </div>
        <Navbar />
        {children}
        <About />
      </body>
    </html>
  )
}
