import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/components/navbar"
import About from '@/components/about'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Guess that City',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <head>
        <title>Guess That City!</title>
      </head>
      <body className={inter.className +" h-screen"}>
        <Navbar></Navbar>
        {children}
        <About></About>
      </body>
    </html>
  )
}
